! Generated by scripts/generate_lapack_bindings.py.
! Stable C dispatch ABI; compiler-specific LAPACK ABI stays in Fortran.
integer(c_int) function ofort_lapack_backend_version() bind(C)
use iso_c_binding, only: c_int
ofort_lapack_backend_version = 1
end function

subroutine ofort_lapack_dispatch(routine, args) bind(C)
use iso_c_binding
implicit none
integer(c_int), value :: routine
type(c_ptr), intent(in) :: args(*)
select case (routine)
case (0)
   block
      integer(c_int), pointer :: n
      integer(c_int), pointer :: nrhs
      real(c_double), pointer :: a(:)
      integer(c_int), pointer :: lda
      integer(c_int), pointer :: ipiv(:)
      real(c_double), pointer :: b(:)
      integer(c_int), pointer :: ldb
      integer(c_int), pointer :: info
      external :: dgesv
      call c_f_pointer(args(1), n)
      call c_f_pointer(args(2), nrhs)
      call c_f_pointer(args(3), a, [1])
      call c_f_pointer(args(4), lda)
      call c_f_pointer(args(5), ipiv, [1])
      call c_f_pointer(args(6), b, [1])
      call c_f_pointer(args(7), ldb)
      call c_f_pointer(args(8), info)
      call dgesv(n, nrhs, a, lda, ipiv, b, ldb, info)
   end block
case (1)
   block
      integer(c_int), pointer :: m
      integer(c_int), pointer :: n
      real(c_double), pointer :: a(:)
      integer(c_int), pointer :: lda
      integer(c_int), pointer :: ipiv(:)
      integer(c_int), pointer :: info
      external :: dgetrf
      call c_f_pointer(args(1), m)
      call c_f_pointer(args(2), n)
      call c_f_pointer(args(3), a, [1])
      call c_f_pointer(args(4), lda)
      call c_f_pointer(args(5), ipiv, [1])
      call c_f_pointer(args(6), info)
      call dgetrf(m, n, a, lda, ipiv, info)
   end block
case (2)
   block
      integer(c_int), pointer :: n
      real(c_double), pointer :: a(:)
      integer(c_int), pointer :: lda
      integer(c_int), pointer :: ipiv(:)
      real(c_double), pointer :: work(:)
      integer(c_int), pointer :: lwork
      integer(c_int), pointer :: info
      external :: dgetri
      call c_f_pointer(args(1), n)
      call c_f_pointer(args(2), a, [1])
      call c_f_pointer(args(3), lda)
      call c_f_pointer(args(4), ipiv, [1])
      call c_f_pointer(args(5), work, [1])
      call c_f_pointer(args(6), lwork)
      call c_f_pointer(args(7), info)
      call dgetri(n, a, lda, ipiv, work, lwork, info)
   end block
case (3)
   block
      character(kind=c_char), pointer :: uplo
      integer(c_int), pointer :: n
      real(c_double), pointer :: a(:)
      integer(c_int), pointer :: lda
      integer(c_int), pointer :: info
      external :: dpotrf
      call c_f_pointer(args(1), uplo)
      call c_f_pointer(args(2), n)
      call c_f_pointer(args(3), a, [1])
      call c_f_pointer(args(4), lda)
      call c_f_pointer(args(5), info)
      call dpotrf(uplo, n, a, lda, info)
   end block
case (4)
   block
      character(kind=c_char), pointer :: jobz
      character(kind=c_char), pointer :: uplo
      integer(c_int), pointer :: n
      real(c_double), pointer :: a(:)
      integer(c_int), pointer :: lda
      real(c_double), pointer :: w(:)
      real(c_double), pointer :: work(:)
      integer(c_int), pointer :: lwork
      integer(c_int), pointer :: info
      external :: dsyev
      call c_f_pointer(args(1), jobz)
      call c_f_pointer(args(2), uplo)
      call c_f_pointer(args(3), n)
      call c_f_pointer(args(4), a, [1])
      call c_f_pointer(args(5), lda)
      call c_f_pointer(args(6), w, [1])
      call c_f_pointer(args(7), work, [1])
      call c_f_pointer(args(8), lwork)
      call c_f_pointer(args(9), info)
      call dsyev(jobz, uplo, n, a, lda, w, work, lwork, info)
   end block
case (5)
   block
      character(kind=c_char), pointer :: jobvl
      character(kind=c_char), pointer :: jobvr
      integer(c_int), pointer :: n
      real(c_double), pointer :: a(:)
      integer(c_int), pointer :: lda
      real(c_double), pointer :: wr(:)
      real(c_double), pointer :: wi(:)
      real(c_double), pointer :: vl(:)
      integer(c_int), pointer :: ldvl
      real(c_double), pointer :: vr(:)
      integer(c_int), pointer :: ldvr
      real(c_double), pointer :: work(:)
      integer(c_int), pointer :: lwork
      integer(c_int), pointer :: info
      external :: dgeev
      call c_f_pointer(args(1), jobvl)
      call c_f_pointer(args(2), jobvr)
      call c_f_pointer(args(3), n)
      call c_f_pointer(args(4), a, [1])
      call c_f_pointer(args(5), lda)
      call c_f_pointer(args(6), wr, [1])
      call c_f_pointer(args(7), wi, [1])
      call c_f_pointer(args(8), vl, [1])
      call c_f_pointer(args(9), ldvl)
      call c_f_pointer(args(10), vr, [1])
      call c_f_pointer(args(11), ldvr)
      call c_f_pointer(args(12), work, [1])
      call c_f_pointer(args(13), lwork)
      call c_f_pointer(args(14), info)
      call dgeev(jobvl, jobvr, n, a, lda, wr, wi, vl, ldvl, vr, ldvr, work, lwork, info)
   end block
case (6)
   block
      integer(c_int), pointer :: m
      integer(c_int), pointer :: n
      real(c_double), pointer :: a(:)
      integer(c_int), pointer :: lda
      real(c_double), pointer :: tau(:)
      real(c_double), pointer :: work(:)
      integer(c_int), pointer :: lwork
      integer(c_int), pointer :: info
      external :: dgeqrf
      call c_f_pointer(args(1), m)
      call c_f_pointer(args(2), n)
      call c_f_pointer(args(3), a, [1])
      call c_f_pointer(args(4), lda)
      call c_f_pointer(args(5), tau, [1])
      call c_f_pointer(args(6), work, [1])
      call c_f_pointer(args(7), lwork)
      call c_f_pointer(args(8), info)
      call dgeqrf(m, n, a, lda, tau, work, lwork, info)
   end block
case (7)
   block
      integer(c_int), pointer :: m
      integer(c_int), pointer :: n
      integer(c_int), pointer :: k
      real(c_double), pointer :: a(:)
      integer(c_int), pointer :: lda
      real(c_double), pointer :: tau(:)
      real(c_double), pointer :: work(:)
      integer(c_int), pointer :: lwork
      integer(c_int), pointer :: info
      external :: dorgqr
      call c_f_pointer(args(1), m)
      call c_f_pointer(args(2), n)
      call c_f_pointer(args(3), k)
      call c_f_pointer(args(4), a, [1])
      call c_f_pointer(args(5), lda)
      call c_f_pointer(args(6), tau, [1])
      call c_f_pointer(args(7), work, [1])
      call c_f_pointer(args(8), lwork)
      call c_f_pointer(args(9), info)
      call dorgqr(m, n, k, a, lda, tau, work, lwork, info)
   end block
case (8)
   block
      character(kind=c_char), pointer :: jobu
      character(kind=c_char), pointer :: jobvt
      integer(c_int), pointer :: m
      integer(c_int), pointer :: n
      real(c_double), pointer :: a(:)
      integer(c_int), pointer :: lda
      real(c_double), pointer :: s(:)
      real(c_double), pointer :: u(:)
      integer(c_int), pointer :: ldu
      real(c_double), pointer :: vt(:)
      integer(c_int), pointer :: ldvt
      real(c_double), pointer :: work(:)
      integer(c_int), pointer :: lwork
      integer(c_int), pointer :: info
      external :: dgesvd
      call c_f_pointer(args(1), jobu)
      call c_f_pointer(args(2), jobvt)
      call c_f_pointer(args(3), m)
      call c_f_pointer(args(4), n)
      call c_f_pointer(args(5), a, [1])
      call c_f_pointer(args(6), lda)
      call c_f_pointer(args(7), s, [1])
      call c_f_pointer(args(8), u, [1])
      call c_f_pointer(args(9), ldu)
      call c_f_pointer(args(10), vt, [1])
      call c_f_pointer(args(11), ldvt)
      call c_f_pointer(args(12), work, [1])
      call c_f_pointer(args(13), lwork)
      call c_f_pointer(args(14), info)
      call dgesvd(jobu, jobvt, m, n, a, lda, s, u, ldu, vt, ldvt, work, lwork, info)
   end block
case (9)
   block
      integer(c_int), pointer :: n
      integer(c_int), pointer :: nrhs
      complex(c_double_complex), pointer :: a(:)
      integer(c_int), pointer :: lda
      integer(c_int), pointer :: ipiv(:)
      complex(c_double_complex), pointer :: b(:)
      integer(c_int), pointer :: ldb
      integer(c_int), pointer :: info
      external :: zgesv
      call c_f_pointer(args(1), n)
      call c_f_pointer(args(2), nrhs)
      call c_f_pointer(args(3), a, [1])
      call c_f_pointer(args(4), lda)
      call c_f_pointer(args(5), ipiv, [1])
      call c_f_pointer(args(6), b, [1])
      call c_f_pointer(args(7), ldb)
      call c_f_pointer(args(8), info)
      call zgesv(n, nrhs, a, lda, ipiv, b, ldb, info)
   end block
end select
end subroutine ofort_lapack_dispatch
