! Generated by scripts/generate_lapack_bindings.py.
module ofort_lapack_mod
implicit none
private
public :: dgesv, dgetrf, dgetri, dpotrf, dsyev, dgeev, dgeqrf, dorgqr, dgesvd, zgesv
interface
   subroutine dgesv(n, nrhs, a, lda, ipiv, b, ldb, info)
      integer, intent(in) :: n
      integer, intent(in) :: nrhs
      double precision, intent(inout) :: a(*)
      integer, intent(in) :: lda
      integer, intent(out) :: ipiv(*)
      double precision, intent(inout) :: b(*)
      integer, intent(in) :: ldb
      integer, intent(out) :: info
   end subroutine dgesv
   subroutine dgetrf(m, n, a, lda, ipiv, info)
      integer, intent(in) :: m
      integer, intent(in) :: n
      double precision, intent(inout) :: a(*)
      integer, intent(in) :: lda
      integer, intent(out) :: ipiv(*)
      integer, intent(out) :: info
   end subroutine dgetrf
   subroutine dgetri(n, a, lda, ipiv, work, lwork, info)
      integer, intent(in) :: n
      double precision, intent(inout) :: a(*)
      integer, intent(in) :: lda
      integer, intent(in) :: ipiv(*)
      double precision, intent(out) :: work(*)
      integer, intent(in) :: lwork
      integer, intent(out) :: info
   end subroutine dgetri
   subroutine dpotrf(uplo, n, a, lda, info)
      character(len=1), intent(in) :: uplo
      integer, intent(in) :: n
      double precision, intent(inout) :: a(*)
      integer, intent(in) :: lda
      integer, intent(out) :: info
   end subroutine dpotrf
   subroutine dsyev(jobz, uplo, n, a, lda, w, work, lwork, info)
      character(len=1), intent(in) :: jobz
      character(len=1), intent(in) :: uplo
      integer, intent(in) :: n
      double precision, intent(inout) :: a(*)
      integer, intent(in) :: lda
      double precision, intent(out) :: w(*)
      double precision, intent(out) :: work(*)
      integer, intent(in) :: lwork
      integer, intent(out) :: info
   end subroutine dsyev
   subroutine dgeev(jobvl, jobvr, n, a, lda, wr, wi, vl, ldvl, vr, ldvr, work, lwork, info)
      character(len=1), intent(in) :: jobvl
      character(len=1), intent(in) :: jobvr
      integer, intent(in) :: n
      double precision, intent(inout) :: a(*)
      integer, intent(in) :: lda
      double precision, intent(out) :: wr(*)
      double precision, intent(out) :: wi(*)
      double precision, intent(out) :: vl(*)
      integer, intent(in) :: ldvl
      double precision, intent(out) :: vr(*)
      integer, intent(in) :: ldvr
      double precision, intent(out) :: work(*)
      integer, intent(in) :: lwork
      integer, intent(out) :: info
   end subroutine dgeev
   subroutine dgeqrf(m, n, a, lda, tau, work, lwork, info)
      integer, intent(in) :: m
      integer, intent(in) :: n
      double precision, intent(inout) :: a(*)
      integer, intent(in) :: lda
      double precision, intent(out) :: tau(*)
      double precision, intent(out) :: work(*)
      integer, intent(in) :: lwork
      integer, intent(out) :: info
   end subroutine dgeqrf
   subroutine dorgqr(m, n, k, a, lda, tau, work, lwork, info)
      integer, intent(in) :: m
      integer, intent(in) :: n
      integer, intent(in) :: k
      double precision, intent(inout) :: a(*)
      integer, intent(in) :: lda
      double precision, intent(in) :: tau(*)
      double precision, intent(out) :: work(*)
      integer, intent(in) :: lwork
      integer, intent(out) :: info
   end subroutine dorgqr
   subroutine dgesvd(jobu, jobvt, m, n, a, lda, s, u, ldu, vt, ldvt, work, lwork, info)
      character(len=1), intent(in) :: jobu
      character(len=1), intent(in) :: jobvt
      integer, intent(in) :: m
      integer, intent(in) :: n
      double precision, intent(inout) :: a(*)
      integer, intent(in) :: lda
      double precision, intent(out) :: s(*)
      double precision, intent(out) :: u(*)
      integer, intent(in) :: ldu
      double precision, intent(out) :: vt(*)
      integer, intent(in) :: ldvt
      double precision, intent(out) :: work(*)
      integer, intent(in) :: lwork
      integer, intent(out) :: info
   end subroutine dgesvd
   subroutine zgesv(n, nrhs, a, lda, ipiv, b, ldb, info)
      integer, intent(in) :: n
      integer, intent(in) :: nrhs
      complex(kind=kind(1.0d0)), intent(inout) :: a(*)
      integer, intent(in) :: lda
      integer, intent(out) :: ipiv(*)
      complex(kind=kind(1.0d0)), intent(inout) :: b(*)
      integer, intent(in) :: ldb
      integer, intent(out) :: info
   end subroutine zgesv
end interface
end module ofort_lapack_mod
