"""Generate the small, matching C/Fortran LAPACK interface tables."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
# Argument types: i INTEGER scalar, c CHARACTER scalar, D real64 array,
# I INTEGER array, Z complex(real64) array. Routines use the LP64 LAPACK ABI.
ROUTINES = [
    ("dgesv", "n nrhs a lda ipiv b ldb info", "iiDiIDii", "a b ipiv info", "a b"),
    ("dgetrf", "m n a lda ipiv info", "iiDiIi", "a ipiv info", "a"),
    ("dgetri", "n a lda ipiv work lwork info", "iDiIDii", "a work info", "a ipiv"),
    ("dpotrf", "uplo n a lda info", "ciDii", "a info", "a"),
    ("dsyev", "jobz uplo n a lda w work lwork info", "cciDiDDii", "a w work info", "a"),
    ("dgeev", "jobvl jobvr n a lda wr wi vl ldvl vr ldvr work lwork info",
     "cciDiDDDiDiDii", "a wr wi vl vr work info", "a"),
    ("dgeqrf", "m n a lda tau work lwork info", "iiDiDDii", "a tau work info", "a"),
    ("dorgqr", "m n k a lda tau work lwork info", "iiiDiDDii", "a work info", "a tau"),
    ("dgesvd", "jobu jobvt m n a lda s u ldu vt ldvt work lwork info",
     "cciiDiDDiDiDii", "a s u vt work info", "a"),
    ("zgesv", "n nrhs a lda ipiv b ldb info", "iiZiIZii", "a b ipiv info", "a b"),
]


def generate() -> None:
    destination = ROOT / "bindings" / "lapack"
    destination.mkdir(parents=True, exist_ok=True)
    interfaces = ["! Generated by scripts/generate_lapack_bindings.py.",
                  "module ofort_lapack_mod", "implicit none", "private",
                  "public :: " + ", ".join(r[0] for r in ROUTINES), "interface"]
    bridge = ["! Generated by scripts/generate_lapack_bindings.py.",
              "! Stable C dispatch ABI; compiler-specific LAPACK ABI stays in Fortran.",
              "integer(c_int) function ofort_lapack_backend_version() bind(C)",
              "use iso_c_binding, only: c_int", "ofort_lapack_backend_version = 1",
              "end function", "",
              "subroutine ofort_lapack_dispatch(routine, args) bind(C)",
              "use iso_c_binding", "implicit none", "integer(c_int), value :: routine",
              "type(c_ptr), intent(in) :: args(*)", "select case (routine)"]
    table = ["/* Generated by scripts/generate_lapack_bindings.py. */",
             "static const OfortLapackRoutine lapack_routines[] = {"]
    for number, (name, names, types, outputs, inputs) in enumerate(ROUTINES):
        names = names.split()
        outputs, inputs = set(outputs.split()), set(inputs.split())
        assert len(names) == len(types)
        write_mask = sum(1 << i for i, arg in enumerate(names) if arg in outputs)
        read_mask = sum(1 << i for i, arg in enumerate(names) if arg in inputs)
        table.append('    {"%s", "%s", {%s}, %du, %du},' % (
            name, types, ", ".join('"' + arg + '"' for arg in names), write_mask, read_mask))
        interfaces.append("   subroutine " + name + "(" + ", ".join(names) + ")")
        for arg, kind in zip(names, types):
            intent = "inout" if arg in inputs and arg in outputs else "out" if arg in outputs else "in"
            declaration = {"i": "integer", "c": "character(len=1)",
                           "D": "double precision", "I": "integer",
                           "Z": "complex(kind=kind(1.0d0))"}[kind]
            suffix = "(*)" if kind.isupper() else ""
            # A rank-1 explicit-size sequence is intentionally usable with
            # rank-2 matrix actuals, as in the traditional LAPACK interfaces.
            interfaces.append(f"      {declaration}, intent({intent}) :: {arg}{suffix}")
        interfaces.append("   end subroutine " + name)
        bridge.extend([f"case ({number})", "   block"])
        for arg, kind in zip(names, types):
            declaration = {"i": "integer(c_int)", "c": "character(kind=c_char)",
                           "D": "real(c_double)", "I": "integer(c_int)",
                           "Z": "complex(c_double_complex)"}[kind]
            suffix = "(:)" if kind.isupper() else ""
            bridge.append(f"      {declaration}, pointer :: {arg}{suffix}")
        bridge.append("      external :: " + name)
        for i, (arg, kind) in enumerate(zip(names, types), 1):
            shape = ", [1]" if kind.isupper() else ""
            bridge.append(f"      call c_f_pointer(args({i}), {arg}{shape})")
        bridge.append("      call " + name + "(" + ", ".join(names) + ")")
        bridge.append("   end block")
    interfaces.extend(["end interface", "end module ofort_lapack_mod", ""])
    bridge.extend(["end select", "end subroutine ofort_lapack_dispatch", ""])
    table.append("};\n")
    for filename, lines in [(destination / "ofort_lapack_mod.f90", interfaces),
                            (destination / "ofort_lapack_backend.f90", bridge),
                            (ROOT / "src" / "ofort_lapack_signatures.inc", table)]:
        filename.write_text("\n".join(lines), encoding="ascii")


if __name__ == "__main__":
    generate()
