"""Create a python_mod source copy that imports compiled LAPACK routines.

The original source is retained. Run the generated copy with xpython.f90,
omitting lapack_d.f90. Compiled builds also need the Fortran interface module.
"""
import argparse
from pathlib import Path
import re

from generate_lapack_bindings import ROUTINES

ROOT = Path(__file__).resolve().parents[1]
INTERFACE = re.compile(r"(?ms)^([ \t]*)interface[ \t]*\n(.*?)^\1end interface[ \t]*$")
PROCEDURE = re.compile(r"(?im)^[ \t]*(?:pure\s+)?(?:integer\s+)?(?:function|subroutine)\s+\w+\s*\(")


def prepare(source: str) -> str:
    supported = {r[0] for r in ROUTINES}
    edits = []
    imports = {}
    for block in INTERFACE.finditer(source):
        names = re.findall(r"(?im)^\s*subroutine\s+(\w+)\s*\(", block.group(2))
        if not names or not set(map(str.lower, names)) <= supported:
            continue
        headers = list(PROCEDURE.finditer(source, 0, block.start()))
        if not headers:
            raise ValueError("LAPACK interface has no enclosing procedure")
        header = headers[-1]
        insertion = source.find("\n", header.end()) + 1
        while source[:insertion].rstrip().endswith("&"):
            insertion = source.find("\n", insertion) + 1
            if insertion == 0:
                raise ValueError("Unterminated procedure header")
        imports.setdefault(insertion, set()).update(map(str.lower, names))
        edits.append((block.start(), block.end(), ""))
    if not imports:
        raise ValueError("No supported LAPACK interfaces found")
    for position, names in imports.items():
        edits.append((position, position, "         use ofort_lapack_mod, only: " + ", ".join(sorted(names)) + "\n"))
    for start, end, replacement in sorted(edits, reverse=True):
        source = source[:start] + replacement + source[end:]
    return "! Generated by scripts/prepare_python_lapack.py; edit the original source.\n" + source


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", nargs="?", type=Path, default=ROOT / "python.f90")
    parser.add_argument("--output", type=Path, default=ROOT / "bindings/lapack/python_native.f90")
    args = parser.parse_args()
    try:
        result = prepare(args.source.read_text(encoding="utf-8-sig"))
        args.output.write_text(result, encoding="utf-8")
    except (OSError, ValueError) as error:
        parser.error(str(error))
    print(f"Saved {args.output}")


if __name__ == "__main__":
    main()
