"""Generate build provenance without changing an unchanged header."""

import argparse
import json
from pathlib import Path
import re
import subprocess


def build_commit(root):
    def git(*args):
        return subprocess.run(
            ["git", *args], cwd=root, check=True, capture_output=True,
            text=True, timeout=5,
        ).stdout.strip()

    try:
        # Do not accidentally use a parent repository for an unpacked archive.
        if Path(git("rev-parse", "--show-toplevel")).resolve() != root.resolve():
            return "unknown"
        commit = git("rev-parse", "--short=12", "HEAD")
        if not re.fullmatch(r"[0-9a-fA-F]{12,40}", commit):
            return "unknown"
        dirty = git("status", "--porcelain", "--untracked-files=no")
        return commit + ("-dirty" if dirty else "")
    except (OSError, subprocess.SubprocessError):
        return "unknown"


def main():
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", type=Path, default=root)
    parser.add_argument("--output", type=Path,
                        default=root / "include" / "ofort_build_version.h")
    args = parser.parse_args()
    contents = (
        "/* Generated by scripts/write_build_version.py; do not edit. */\n"
        "#ifndef OFORT_BUILD_VERSION_H\n"
        "#define OFORT_BUILD_VERSION_H\n"
        f"#define OFORT_BUILD_COMMIT {json.dumps(build_commit(args.repo))}\n"
        "#endif\n"
    )
    try:
        if args.output.read_text(encoding="ascii") == contents:
            return
    except FileNotFoundError:
        pass
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(contents, encoding="ascii")


if __name__ == "__main__":
    main()
